[package]
name = "ddust1n/zoneplus"
description = "A fork of 1foreverhd's zoneplus, fixed for wally."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "3.2.3"
exclude = [
	"docs", ".moonwave", "test",
	"ZonePlus.rbxm", "ZonePlus.rbxmx",
	".gitignore", "foreman.toml",
]

[dependencies]