[package]
name = "ddust1n/zoneplus"
description = "A fork of 1foreverhd's zoneplus, fixed for wally."
version = "3.2.5"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/**", "default.project.json", "LICENSE", "wally.toml"]

[dependencies]